import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import NavLinks from "./ui/NavLinks"

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <NavLinks links={[{ linkName: 'bookshelf', url: '/' }, { linkName: 'write', url: '/write' }]} />{children}
      </body>
    </html>
  )
}
